### ISSUE TITLE
今の構想をまとめる

### ISSUE THREAD

**Issue by hiurawork** [sohdai-sakuramoto/termbook#14]
現状、考えている構想をまとめる。（いまのうちに洗い出しておく）

* いつまでに、どの機能を作ってリリースしたいか。
* 今後、どんな機能を追加していきたいか。
* 利用層、利用者数はどうか。
* システムの利用形態はどうか(サブスクリプション?)

等

**Comment by sohdai-sakuramoto** [comment]
こんな感じ
git@github.com:sohdai-sakuramoto/termbook.git
